### ISSUE TITLE
프로토콜을 지정하지 않았을때 처리

### ISSUE THREAD

**Issue by kybin** [coldmine/urlcheck#4]
현재는 `urlcheck www.naver.com`을 하면 다음과 같은 에러가 나요.
` ERR   0 www.naver.com : Get www.naver.com: unsupported protocol scheme ""`

제가 프로토콜을 지정하지 않아도 자동으로 프로토콜을 붙여줬으면 좋겠어요.
처음에는 https로 검색하고, 없을경우 http로, 그래도 없으면 에러를 내면 어떨까요?

**Comment by khw7096** [comment]
저도 그 생각을 해봤는데, 사용자가 체크하고 싶은 프로토콜을 확실하게 입력하는게 맞을것 같기도 해요.
체크하고 싶은게 확실하게 https인지 http인지도 사용자가 판단해야하거든요.
대부분 웹서버들이 2개를 혼용하며 아이콘, 보안과 관련없는 설정등은 http로 로그인 부분 보안부분은 https로 구현해 놓는 경우가 있어서 어떤 서버를 체크하고 있는가를 자동으로 판단하면 모호해진다고 생각해요.

**Comment by khw7096** [comment]
특히나 애플제품에서 열어야하는 사이트는 그런 경향이 있었어요.
https에서는 아이패드, 아이폰에서 아이콘을 못불러와서 같은 도메인의 http서버를 따로 개설하거나, http는 다른 서버를 사용하거나 하더라구요.

**Comment by kybin** [comment]
현재 메시지에 프로토콜이 나오는 구조라서 크게 문제는 없을것 같은데요.

```
  OK 200 http://www.github.com
```

또는 프로토콜을 지정하지 않았을 때 양쪽을 다 검색하는 것도 방법인것 같아요.

```
  OK 200 https://www.github.com
  OK 200 http://www.github.com
```

만약 그걸 원하지 않으면 에러 메시지는 조금 더 다듬어야 할것 같아요. 현재는 내가 무슨 잘못을 했는지 알아보기가 어려워요.

**Comment by khw7096** [comment]
추후 다른 스크립트와의 연동을 위해서 한개의 인풋은 한개의 아웃풋으로 .. 처리할 예정이라눙..
